== DutyCal: Duty Scheduling Calendar Integrated With Google Calendar

=== Problem

This is similar to the https://en.wikipedia.org/wiki/Nurse_scheduling_problem[Nurse Scheduling Problem].

The goal is to schedule duty for participants in a fair way, where each participants are only available some of the time, and each participant is only allowed to have a maximum of one duty per day.


=== Overview
The application has three tabs:
. Availability
. Schedule
. Summary (optional, may show some totals)
. Settings (for Admin only)


=== Usage

==== For Admin
. Click "Login using Google" to access the application
. On "Settings" tab, enter:
.. scheduling dates (FROM, TO)
.. how many duties per day (NUMBER)
.. define algorithm precision (TODO this is yet discussed)
. Click "Create schedule"
. Once the schedule is created, display it (is this step really needed? Would you like to have an ability to manually edit the schedule? Or you would like to be sure in what you are posting and change algorithm settings in case?)
. Click "Send to Google Calendar" to **publish** it at the users' Google Calendars

==== For User
. Click "Login using Google" to access the application
. Enter or change user's availability using our representation of calendar with checkboxes next to each day (important: this will require central database for storing availability)
. Click "Create (Update) Schedule" to save the changes and update the schedule
. View user's schedule on the "Schedule" tab
. Get link to user's Google Calendar, where schedule and availability would be displayed


=== Google Calendar Integration

Google Calendar is used to:

* NOT store availability of participants (in a calendar called "availability"), BECAUSE
.. it's hard to add and remove availability for user, checkboxes work far better
.. **I did not yet find an option to show "only your events" on the calendar. Therefore events from other 200+ users would be always visible, which will bloat the calendar and make it unusable**
.. also, every user would see availability of others and change it, which is not secure
.. same for duty calendar. It will show duties for other users as well, not for single user
.. adding new user would require admin to add access rights, which is not very user friendly (10+ seconds per user)
.. PS: instead, adding user's to a file would be enough

* As a result, Google Calendar is useful only for displaying and sharing availability / duties, not for managing them.


=== Definitions

P::
  Array of people to assign duty to. There are n number of people, represented by `P_0 ...P_n`.

S::
  Array (continuous or disjoint) of schedulable days: `S_0 ... S_m`.

A::
  Array of person availability. Each person `P_i` has available days `A_p ... A_q`, where each `A_x` is within S.

d::
  Integer. The desired number of scheduled duties per day for every `S_x` day.

D_{u, x}::
  A duty assignment for day `S_u` on the `x`-th slot, where `S_u` is within S and `0 <= x <= d`.


=== Constraints


==== HARD Constraints

* There are only `d` duty slots a day.
* 1 person can only have max 1 duty a day.
* Availability is by DAY not by TIME.


==== SOFT Constraints

Fairness::
  The variance between number of duties of all `P_i` and `P_j`, i.e. `Duties(P_i)` => `e`, `Duties (P_j)` => `f`, `|e - f|` must be minimal for all pairs.

Distributed::
  The number of days of duty should be as spread out as evenly as possible, such that for `P_i`'s duty days, `S_x` ... `S_y` where `x` is between `0` and `m`.

Stable::
  Changing (adding, removing) one `P_i`'s `A_x` where `p <= x <= q`, should result in a minimal change in `P_j`'s schedules (preferably only another `P_j` but not other `P_`). Intent: one person's update would cause minimal changes to other people's schedule, so the impact to others' duties would be minimal.

Order of importance: Stability >>> Fairness > Distributed.


=== Output

For each person `P_i`, output a schedule:

----
L_i = D_{u, x} ... D_{w, y}
----

Where `0 <= u < w <= m`, `0 <= x, y <= d`, `u` and `w` are elements in `{p ... q}`.

The goal is to find all `L_{P_i}` for all `i`, where `0 <= i <= n`.


=== Potential Techniques

* https://en.wikipedia.org/wiki/Local_search_(optimization)[Local search]
** https://link.springer.com/chapter/10.1007/978-3-642-27245-5_25[Stochastic Local Search Approaches in Solving the Nurse Scheduling Problem, 2011]

* https://en.wikipedia.org/wiki/Branch_and_bound[Branch-and-bound]
** http://ieeexplore.ieee.org/document/7021791/[New Solution for a Benchmark Nurse Scheduling Problem Using Integer Programming, 2014]

* https://en.wikipedia.org/wiki/Simulated_annealing[Simulated Annealing]
** http://ieeexplore.ieee.org/document/4341767/[Simulated Annealing Algorithm for Daily Nursing Care Scheduling Problem, 2007]
** http://www.columbia.edu/~cs2035/courses/ieor4405.S17/p23.pdf

* https://en.wikipedia.org/wiki/Genetic_algorithm[Genetic]
** http://ieeexplore.ieee.org/document/934317/[Genetic algorithm with the constraints for nurse scheduling problem, 2001]
** https://www.math.cmu.edu/~af1p/Teaching/OR2/Projects/P23/ORProject_Final_Copy.pdf

* Mixed
** https://link.springer.com/article/10.1007/s40092-015-0111-0[Maximizing the nurses' preferences in nurse scheduling problem: mathematical modeling and a meta-heuristic algorithm, 2015]

